### ISSUE TITLE
issues with ycm_extra_conf.py

### ISSUE THREAD

**Issue by valerino** [Qusic/atom-youcompleteme#12]
original YCM docs states:
"YCM looks for a .ycm_extra_conf.py file in the directory of the opened file or in any directory above it in the hierarchy (recursively)" 

this is not honored in atom-youcompleteme, it always use the file provided in 'Global Extra Config' settings to launch ycmd. Thus, you can't use per-project settings but you always have to change the plugin configuration ......

please look into this asap :)

**Comment by valerino** [comment]
i've fixed it myself in my own repo, you have a pull request!

**Comment by sztomi** [comment]
This commit is not the one selected by the install script, it should be changed.

**Comment by rubber-duck** [comment]
So how do I add custom c++ include paths to YCM without this (eg. if my project is structured like project/include and project/src) ?

**Comment by Qusic** [comment]
done
