### ISSUE TITLE
Requirements are not listed and they are not obvious for someone not familiar with node

### ISSUE THREAD

**Issue by sztomi** [Qusic/atom-youcompleteme#14]
I was trying to install this package on Ubuntu 15.04 but ran into the following problems. 

  * It requires command line installation instead of installing from Atom
  * It requires coffeescript which is not installed by default
  * It requires a nodejs which is not installed by default
  * The nodejs version it requires is older than the one provided by Ubuntu

After some experimentation, I found that a working way to install it was:

  * Optional: uninstall any system-installed nodejs, npm, node-*, coffeescript packages
  * Install [nvm](https://github.com/creationix/nvm)
  * `nvm install 0.12.4` (or some other version, this is the latest at the time of writing this)
  * `npm install -g coffee-script`

I think these requirements should be indicated to the user otherwise it's pretty hard to get started.

**Comment by Qusic** [comment]
done.
