### ISSUE TITLE
atom-ycm ignores python interpreter settings

### ISSUE THREAD

**Issue by fufler** [Qusic/atom-youcompleteme#18]
It seems that atom-ycm ignores python interpreter configured from package settings.  Take a look at https://github.com/Qusic/atom-youcompleteme/blob/master/lib/update-dependencies.coffee#L20: it uses python executable to run the code. In my system /usr/bin/python is simlinked to /usr/bin/python3 so this code fails to run. There are at least two possible solutions: use configured interpeter (or maybe just python2 always?) or use syntax that is compatible with both 2 and 3 version.

**Comment by Kuxe** [comment]
I can confirm this.

My "Python Executable" in settings is set to "/usr/bin/python2". With this setting the extraWarning 'Ycmd native parts have to be recompiled before it works.' displays.

If change "python" to "/usr/bin/python2" in https://github.com/Qusic/atom-youcompleteme/blob/master/lib/update-dependencies.coffee#L20, the warning disappears. Still ycmd doesn't work for me, but I think that's another unrelated issue..

**Comment by Qusic** [comment]
Fixed.
