### ISSUE TITLE
Support for project-specific ycm extra config

### ISSUE THREAD

**Issue by fufler** [Qusic/atom-youcompleteme#19]
YCM supports project-specific extra configuration files, that can be loaded automatically from current folder (or one of the parent folders). At the moment these file are not loaded because with default settings YCM requires load confirmation. Please, provide an option to disable extra config loading confirmation, because the only way to load extra config now is to apply this patch to YCM:

```diff
@@ -13,7 +13,7 @@
   "max_num_identifier_candidates": 10,
   "extra_conf_globlist": [],
   "global_ycm_extra_conf": "",
-  "confirm_extra_conf": 1,
+  "confirm_extra_conf": 0,
   "complete_in_comments": 0,
   "complete_in_strings": 1,
   "max_diagnostics_to_display": 30,
```

**Comment by fufler** [comment]
Sorry, missed the one that already existed.

**Comment by dragonxlwang** [comment]
which file can change the ycm settings?
