### ISSUE TITLE
First request sent before ycmd server is up

### ISSUE THREAD

**Issue by kentonv** [Qusic/atom-youcompleteme#20]
On the first autocomplete event, the atom plugin starts `ycmd` and then immediately attempts to make an HTTP request, which fails because `ycmd` has not started up yet and is not ready to receive connections. An error is printed to the console like:

    [YCM-ERROR] Error: connect ECONNREFUSED 127.0.0.1:41416 {code: "ECONNREFUSED", errno: "ECONNREFUSED", syscall: "connect", address: "127.0.0.1", port: 41416…}

and the request fails. Subsequent requests succeed. Perhaps the plugin should wait a bit for `ycmd` to start up before trying to send a request.

**Comment by henrik-muehe** [comment]
This should be fixed in 0f5e79df0ce2eefaea8dc83c97249a7f71c26406
