### ISSUE TITLE
Why this over something else?

### ISSUE THREAD

**Issue by mikew** [Qusic/atom-youcompleteme#21]
I use YCM in my Vim installation because it solves a bunch of shortcomings with Vim's autocomplete system, and enhances what's already there.

Since Atom comes with autocomplete+, why use `atom-youcompleteme` when there's already `omnisharp-atom`, `go-plus`, `autocomplete-jedi`, `autocomplete-clang`, etc?

Could be useful to put such information in the readme.

**Comment by Furyhunter** [comment]
When this plugin's `ycmd` fork gets updated, it will have a more robust completion engine for Rust than the existing `linter-rust` and `racer` packages, so it seems to be the preferred option for Rust developers now.

I've had performance issues and long startup times with `omnisharp-atom` even outside of C# projects.

**Comment by kkHAIKE** [comment]
you can try the master branch for best completion.
cuz the repo master so busy and my poor english.
sorry about the readme......

**Comment by kkHAIKE** [comment]
i think YCM is better than `autocomplete-clang`.
cuz the second get complete by call 'clang.exe', to slow for large project.

**Comment by Qusic** [comment]
YouCompleteMe has been around for some time and its features and performance is time-proven. And it is also convenient to have only one installation of YCM and use it in both vim and atom.
