### ISSUE TITLE
Python version used on Archlinux

### ISSUE THREAD

**Issue by rogrmil** [Qusic/atom-youcompleteme#28]
On Archlinux, the plugin does not run (always gives an error stating that it needs to be recompiled), since the plugin expects the `python` command to run `python2`, but arch linux links to `python3` instead. This can be fixed by the following config.coffee:
```
module.exports =
  pythonExecutable:
    type: 'string'
    default: 'python2'
...
```
but it would be nice if this was automated/mentioned in the README

**Comment by Qusic** [comment]
Thanks for the feedback. I have updated README for that.
