### ISSUE TITLE
Crashes every single time

### ISSUE THREAD

**Issue by bdsun** [Qusic/atom-youcompleteme#29]
Process:               Python [99859]
Path:                  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               2.7.10 (2.7.10)
Code Type:             X86-64 (Native)
Parent Process:        Atom Helper [98569]
Responsible:           Atom [98563]
User ID:               1918221424

PlugIn Path:             /usr/local/Frameworks/Python.framework/Versions/2.7/Python
PlugIn Identifier:       org.python.python
PlugIn Version:          2.7.10, [c] 2001-2015 Python Software Foundation. (2.7.10)

Date/Time:             2015-09-03 15:21:52.183 -0500
OS Version:            Mac OS X 10.10.5 (14F27)
Report Version:        11
Anonymous UUID:        DD45B78C-549D-086C-108C-08D9CDCE17B9

Sleep/Wake UUID:       ECE87828-012D-4AA6-881E-D4769412880B

Time Awake Since Boot: 890000 seconds
Time Since Wake:       880000 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff91c03286 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff893749b3 abort + 129
2   org.python.python             	0x000000010b5eea9a Py_FatalError + 49
3   org.python.python             	0x000000010b5edfa8 PyThreadState_Get + 28
4   org.python.python             	0x000000010b5eaeb2 Py_InitModule4_64 + 62
5   ycm_core.so                   	0x000000010b385d43 boost::python::detail::init_module(char const*, void (*)()) + 35
6   org.python.python             	0x000000010a96697b _PyImport_LoadDynamicModule + 140
7   org.python.python             	0x000000010a966663 0x10a8ca000 + 640611
8   org.python.python             	0x000000010a96622d 0x10a8ca000 + 639533
9   org.python.python             	0x000000010a964436 PyImport_ImportModuleLevel + 1135
10  org.python.python             	0x000000010a9499b3 0x10a8ca000 + 522675
11  org.python.python             	0x000000010a8d450a PyObject_Call + 99
12  org.python.python             	0x000000010a9543df PyEval_CallObjectWithKeywords + 93
13  org.python.python             	0x000000010a950641 PyEval_EvalFrameEx + 8379
14  org.python.python             	0x000000010a954c82 0x10a8ca000 + 568450
15  org.python.python             	0x000000010a9519a6 PyEval_EvalFrameEx + 13344
16  org.python.python             	0x000000010a954c82 0x10a8ca000 + 568450
17  org.python.python             	0x000000010a9519a6 PyEval_EvalFrameEx + 13344
18  org.python.python             	0x000000010a94e352 PyEval_EvalCodeEx + 1409
19  org.python.python             	0x000000010a952768 PyEval_EvalFrameEx + 16866
20  org.python.python             	0x000000010a94e352 PyEval_EvalCodeEx + 1409
21  org.python.python             	0x000000010a954bf1 0x10a8ca000 + 568305
22  org.python.python             	0x000000010a9519a6 PyEval_EvalFrameEx + 13344
23  org.python.python             	0x000000010a94e352 PyEval_EvalCodeEx + 1409
24  org.python.python             	0x000000010a8f25de 0x10a8ca000 + 165342
25  org.python.python             	0x000000010a8d450a PyObject_Call + 99
26  org.python.python             	0x000000010a97f6e1 0x10a8ca000 + 743137
27  org.python.python             	0x000000010a97f566 Py_Main + 3354
28  libdyld.dylib                 	0x00007fff907db5c9 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff55338a08  rdx: 0x0000000000000000
  rdi: 0x0000000000000d0f  rsi: 0x0000000000000006  rbp: 0x00007fff55338a30  rsp: 0x00007fff55338a08
   r8: 0x00007fff55338a20   r9: 0x00007fff74ab1300  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x00007fa72402e000  r13: 0x000000010b3db10c  r14: 0x00007fff74ab1300  r15: 0x000000010aa03548
  rip: 0x00007fff91c03286  rfl: 0x0000000000000206  cr2: 0x00007fff73a6cfd8
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

Binary Images:
       0x10a8c6000 -        0x10a8c6fff  org.python.python (2.7.10 - 2.7.10) <109A7A4A-99AF-338A-86CC-6D17F5EC88A6> /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
       0x10a8ca000 -        0x10a9bcfff  org.python.python (2.7.10 - 2.7.10) <E4356925-959C-36B1-9991-1D925E7B6C94> /System/Library/Frameworks/Python.framework/Versions/2.7/Python
       0x10ab86000 -        0x10ab87fff  _locale.so (89.40.1) <59549509-EE3A-300A-8C68-49F1FBEBE2DC> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_locale.so
       0x10ac8b000 -        0x10ac9afff  _io.so (89.40.1) <D1BE6B16-14FE-364F-BA9C-F53510B67E45> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
       0x10acab000 -        0x10acaeff7  math.so (89.40.1) <3016B791-FC4B-3B04-82F2-7941EB5CC347> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/math.so
       0x10acb4000 -        0x10acb6fff  binascii.so (89.40.1) <F21ADE6F-29F9-34EA-BCDD-EABA8FBD23DF> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/binascii.so
       0x10acba000 -        0x10acbbfff  _hashlib.so (89.40.1) <FF03A044-74E2-3DF9-894D-1C322421D6EF> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_hashlib.so
       0x10acc0000 -        0x10acf6ff7  libssl.0.9.8.dylib (52.40.1) <0121FFA1-8332-39FF-9542-3E80BBC323D7> /usr/lib/libssl.0.9.8.dylib
       0x10ad0c000 -        0x10ad0ffff  _struct.so (89.40.1) <2443B9A8-9F7E-3620-A009-A545E8C16719> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_struct.so
       0x10ad15000 -        0x10ad16ff7  _random.so (89.40.1) <6BEAED69-3F2E-377C-82C8-AC6D99A55F5E> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_random.so
       0x10ad1a000 -        0x10ad1bfff  cStringIO.so (89.40.1) <397642F6-410C-3229-8602-F81EB3DDCBFE> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/cStringIO.so
       0x10ad20000 -        0x10ad21fff  fcntl.so (89.40.1) <572598F0-FCF9-3821-AB50-CE6215E13C08> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/fcntl.so
       0x10ad25000 -        0x10ad26fff  _functools.so (89.40.1) <C3591409-0F95-32BE-ADE0-4B61CACE6260> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_functools.so
       0x10ad2a000 -        0x10ad31ff7  _socket.so (89.40.1) <942FC773-142B-364E-AC99-EB24A5D5D029> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_socket.so
       0x10ad3b000 -        0x10ad44fff  _ssl.so (89.40.1) <62B0751A-A0D4-3B99-BCB3-54F88A921B11> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
       0x10ad4f000 -        0x10ad53fff  _json.so (89.40.1) <15B203E1-4CBD-3615-AA88-B876DCF9081A> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_json.so
       0x10add8000 -        0x10add9fff  time.so (89.40.1) <9E1F6DA2-9AF6-3881-945B-60E1960EEAE7> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/time.so
       0x10addf000 -        0x10ade1fff  select.so (89.40.1) <B9C0E564-2854-3829-8107-AD47E3044C80> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/select.so
       0x10ade7000 -        0x10ade9fff  _collections.so (89.40.1) <AC77804C-F5F9-3EE7-B03B-8B2E373C5C79> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_collections.so
       0x10adef000 -        0x10adf2fff  operator.so (89.40.1) <557EF3D6-7532-3AA9-8F4F-F3637E714414> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/operator.so
       0x10adf8000 -        0x10adfcfff  itertools.so (89.40.1) <FC1B2B69-A09D-3DFC-8AFF-9DAA201EF29A> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/itertools.so
       0x10ae05000 -        0x10ae06fff  _heapq.so (89.40.1) <BBBA9D12-5692-3BA2-A54D-ECCF618EEA91> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_heapq.so
       0x10af8b000 -        0x10af8eff7  strop.so (89.40.1) <3E094406-6B2D-3030-9B8C-F54A7998962F> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/strop.so
       0x10b013000 -        0x10b017fff  array.so (89.40.1) <27DCF036-1728-3300-B537-8A285A61439D> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/array.so
       0x10b0dd000 -        0x10b0e6fff  datetime.so (89.40.1) <DAAF704F-A84D-3028-92CD-5D5EB9A14635> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/datetime.so
       0x10b1af000 -        0x10b1affff  _scproxy.so (89.40.1) <42F89A22-64CE-3428-B207-2823F0665B7F> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_scproxy.so
       0x10b233000 -        0x10b2d7fff  unicodedata.so (89.40.1) <3C49828D-B338-3377-904B-D7F65D6AC256> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/unicodedata.so
       0x10b2dd000 -        0x10b2e8fff  cPickle.so (89.40.1) <8F420BF2-F4D7-3E7F-A458-5569C75D5602> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/cPickle.so
       0x10b2ee000 -        0x10b3eefff +ycm_core.so (0) <E8DD9A23-B0D8-3B37-AB17-8940FBF1810C> /Users/USER/*/ycm_core.so
       0x10b54c000 -        0x10b63dfff +org.python.python (2.7.10, [c] 2001-2015 Python Software Foundation. - 2.7.10) <5D0AE21E-77B6-345E-B3A2-4DD5429C2327> /usr/local/Frameworks/Python.framework/Versions/2.7/Python
       0x10b6bc000 -        0x10c1acff3 +libclang.dylib (0) <25F04EE2-06AE-3201-AF49-F84C26DF522C> /Users/USER/*/libclang.dylib
       0x10c3df000 -        0x10c3fdfff  libedit.3.dylib (40) <6049084C-478A-3A89-A9A1-E641B5F8C1A7> /usr/lib/libedit.3.dylib
    0x7fff6efe7000 -     0x7fff6f01d887  dyld (353.2.3) <B1B370A5-479F-3533-8AD7-97B687D4F989> /usr/lib/dyld
    0x7fff82748000 -     0x7fff8274cfff  libcache.dylib (69) <45E9A2E7-99C4-36B2-BEE3-0C4E11614AD1> /usr/lib/system/libcache.dylib
    0x7fff82c66000 -     0x7fff82c6fff7  libsystem_notify.dylib (133.1.1) <61147800-F320-3DAA-850C-BADF33855F29> /usr/lib/system/libsystem_notify.dylib
    0x7fff82fa2000 -     0x7fff82fa7ff7  libmacho.dylib (862) <126CA2ED-DE91-308F-8881-B9DAEC3C63B6> /usr/lib/system/libmacho.dylib
    0x7fff830c5000 -     0x7fff830f5ff7  libncurses.5.4.dylib (44) <F09809A4-53B9-3E91-A8FA-D3F584C03AA3> /usr/lib/libncurses.5.4.dylib
    0x7fff83300000 -     0x7fff83301ff3  libSystem.B.dylib (1213) <1866C519-C5F3-3D09-8C17-A8F703664521> /usr/lib/libSystem.B.dylib
    0x7fff83803000 -     0x7fff83849ff7  libauto.dylib (186) <A260789B-D4D8-316A-9490-254767B8A5F1> /usr/lib/libauto.dylib
    0x7fff8395b000 -     0x7fff83983fff  libsystem_info.dylib (459.40.1) <2E16C4B3-A327-3957-9C41-143911979A1E> /usr/lib/system/libsystem_info.dylib
    0x7fff83ac7000 -     0x7fff83afffff  libsystem_network.dylib (412.20.3) <6105C134-6722-3C0A-A4CE-5E1261E2E1CC> /usr/lib/system/libsystem_network.dylib
    0x7fff84170000 -     0x7fff841e9fe7  libcorecrypto.dylib (233.30.1) <5779FFA0-4D9A-3AD4-B7F2-618227621DC8> /usr/lib/system/libcorecrypto.dylib
    0x7fff8487e000 -     0x7fff84886fff  libsystem_platform.dylib (63) <64E34079-D712-3D66-9CE2-418624A5C040> /usr/lib/system/libsystem_platform.dylib
    0x7fff849b8000 -     0x7fff849d4ff7  libsystem_malloc.dylib (53.30.1) <DDA8928B-CC0D-3255-BD8A-3FEA0982B890> /usr/lib/system/libsystem_malloc.dylib
    0x7fff8562a000 -     0x7fff8562bffb  libremovefile.dylib (35) <3485B5F4-6CE8-3C62-8DFD-8736ED6E8531> /usr/lib/system/libremovefile.dylib
    0x7fff8584b000 -     0x7fff85a30ff7  libicucore.A.dylib (531.48) <3CD34752-B1F9-31D2-865D-B5B0F0BE3111> /usr/lib/libicucore.A.dylib
    0x7fff85abe000 -     0x7fff85cb846f  libobjc.A.dylib (647) <759E155D-BC42-3D4E-869B-6F57D477177C> /usr/lib/libobjc.A.dylib
    0x7fff85cba000 -     0x7fff85cc5fff  libcommonCrypto.dylib (60061.30.1) <E789748D-F9A7-3CFF-B317-90DF348B1E95> /usr/lib/system/libcommonCrypto.dylib
    0x7fff85cff000 -     0x7fff85d05ff7  libsystem_networkextension.dylib (167.40.3) <BA58B30B-8377-3B0A-8AE3-4F84021D9D4E> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff85d19000 -     0x7fff85d2aff7  libz.1.dylib (55) <88C7C7DE-04B8-316F-8B74-ACD9F3DE1AA1> /usr/lib/libz.1.dylib
    0x7fff85d56000 -     0x7fff85d58fff  libsystem_configuration.dylib (699.40.2) <56F94DCE-DBDE-3615-8F07-DE6270D9F8BE> /usr/lib/system/libsystem_configuration.dylib
    0x7fff8618f000 -     0x7fff8619fff7  libbsm.0.dylib (34) <A3A2E56C-2B65-37C7-B43A-A1F926E1A0BB> /usr/lib/libbsm.0.dylib
    0x7fff861a0000 -     0x7fff861a7ff7  libcompiler_rt.dylib (35) <BF8FC133-EE10-3DA6-9B90-92039E28678F> /usr/lib/system/libcompiler_rt.dylib
    0x7fff86c84000 -     0x7fff86d68fff  libcrypto.0.9.8.dylib (52.40.1) <D123FC57-E2EB-3E08-A51B-6C317EA83EB5> /usr/lib/libcrypto.0.9.8.dylib
    0x7fff87099000 -     0x7fff8709efff  libsystem_stats.dylib (163.30.2) <D0E96837-3CF6-323D-B711-6DF6F660E530> /usr/lib/system/libsystem_stats.dylib
    0x7fff87928000 -     0x7fff8792afff  libsystem_sandbox.dylib (358.20.5) <3F5E973F-C702-31AC-97BC-05F5C195683C> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff87f62000 -     0x7fff87f73ff3  libsystem_coretls.dylib (35.40.1) <155DA0A9-2046-332E-BFA3-D7974A51F731> /usr/lib/system/libsystem_coretls.dylib
    0x7fff88423000 -     0x7fff88425fff  libquarantine.dylib (76.20.1) <7AF90041-2768-378A-925A-D83161863642> /usr/lib/system/libquarantine.dylib
    0x7fff88aef000 -     0x7fff88b17fff  libxpc.dylib (559.40.1) <5C829202-962E-3744-8B50-00D38CC88E84> /usr/lib/system/libxpc.dylib
    0x7fff88c40000 -     0x7fff88c41ff7  libsystem_blocks.dylib (65) <9615D10A-FCA7-3BE4-AA1A-1B195DACE1A1> /usr/lib/system/libsystem_blocks.dylib
    0x7fff88c42000 -     0x7fff88c42ff7  liblaunch.dylib (559.40.1) <4F81CA3A-D2CE-3030-A89D-42F3DAD7BA8F> /usr/lib/system/liblaunch.dylib
    0x7fff88d1e000 -     0x7fff88d20ff7  libsystem_coreservices.dylib (9) <41B7C578-5A53-31C8-A96F-C73E030B0938> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff89317000 -     0x7fff893a3fe7  libsystem_c.dylib (1044.40.1) <F0635E0F-FE4B-34DB-ACF9-A58C1E9070E9> /usr/lib/system/libsystem_c.dylib
    0x7fff896c3000 -     0x7fff896eefff  libc++abi.dylib (125) <88A22A0F-87C6-3002-BFBA-AC0F2808B8B9> /usr/lib/libc++abi.dylib
    0x7fff898ce000 -     0x7fff898cffff  libsystem_secinit.dylib (18) <581DAD0F-6B63-3A48-B63B-917AF799ABAA> /usr/lib/system/libsystem_secinit.dylib
    0x7fff8b010000 -     0x7fff8b018fff  libsystem_dnssd.dylib (576.30.4) <0CEB5910-843F-315C-A1DE-5D955A48A045> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff8c5e7000 -     0x7fff8c5efffb  libcopyfile.dylib (118.1.2) <0C68D3A6-ACDD-3EF3-991A-CC82C32AB836> /usr/lib/system/libcopyfile.dylib
    0x7fff8d6cf000 -     0x7fff8d6d0fff  libDiagnosticMessagesClient.dylib (100) <2EE8E436-5CDC-34C5-9959-5BA218D507FB> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff8d747000 -     0x7fff8d75dff7  libsystem_asl.dylib (267) <F153AC5B-0542-356E-88C8-20A62CA704E2> /usr/lib/system/libsystem_asl.dylib
    0x7fff8df34000 -     0x7fff8dfacff7  com.apple.SystemConfiguration (1.14.4 - 1.14) <3DFFD7F7-BD23-3F4C-A209-C4A0D99F6573> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff8e6e8000 -     0x7fff8e712ff7  libdispatch.dylib (442.1.4) <502CF32B-669B-3709-8862-08188225E4F0> /usr/lib/system/libdispatch.dylib
    0x7fff8e891000 -     0x7fff8e891ff7  libkeymgr.dylib (28) <77845842-DE70-3CC5-BD01-C3D14227CED5> /usr/lib/system/libkeymgr.dylib
    0x7fff8edfe000 -     0x7fff8ee52fff  libc++.1.dylib (120) <1B9530FD-989B-3174-BB1C-BDC159501710> /usr/lib/libc++.1.dylib
    0x7fff901a8000 -     0x7fff901d8fff  libsystem_m.dylib (3086.1) <1E12AB45-6D96-36D0-A226-F24D9FB0D9D6> /usr/lib/system/libsystem_m.dylib
    0x7fff907d8000 -     0x7fff907dbff7  libdyld.dylib (353.2.3) <CFBBE540-D503-3AFC-B5D6-644F1E69949B> /usr/lib/system/libdyld.dylib
    0x7fff90a40000 -     0x7fff90a45ff7  libunwind.dylib (35.3) <BE7E51A0-B6EA-3A54-9CCA-9D88F683A6D6> /usr/lib/system/libunwind.dylib
    0x7fff90b09000 -     0x7fff90b09ff7  libunc.dylib (29) <5676F7EA-C1DF-329F-B006-D2C3022B7D70> /usr/lib/system/libunc.dylib
    0x7fff9106a000 -     0x7fff91073fff  libsystem_pthread.dylib (105.40.1) <ACE90967-ECD0-3251-AEEB-461E3C6414F7> /usr/lib/system/libsystem_pthread.dylib
    0x7fff91188000 -     0x7fff91520ff7  com.apple.CoreFoundation (6.9 - 1153.18) <5C0892B8-9691-341F-9279-CA3A74D59AA0> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff9193d000 -     0x7fff91943fff  libsystem_trace.dylib (72.20.1) <840F5301-B55A-3078-90B9-FEFFD6CD741A> /usr/lib/system/libsystem_trace.dylib
    0x7fff91bed000 -     0x7fff91c0afff  libsystem_kernel.dylib (2782.40.9) <16AD15EF-3DAE-3F63-9D26-26CCE1920762> /usr/lib/system/libsystem_kernel.dylib
    0x7fff91c30000 -     0x7fff91c31fff  com.apple.TrustEvaluationAgent (2.0 - 25) <2D61A2C3-C83E-3A3F-8EC1-736DBEC250AB> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 459992
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=102.8M resident=48.9M(48%) swapped_out_or_unallocated=53.9M(52%)
Writable regions: Total=80.1M written=10.3M(13%) resident=13.2M(16%) swapped_out=0K(0%) unallocated=66.9M(84%)
 
REGION TYPE                      VIRTUAL
===========                      =======
Kernel Alloc Once                     4K
MALLOC                             70.9M
MALLOC (admin)                       16K
STACK GUARD                        56.0M
Stack                              8192K
VM_ALLOCATE                          12K
__DATA                             2868K
__LINKEDIT                         74.5M
__TEXT                             28.3M
__UNICODE                           552K
shared memory                         4K
===========                      =======
TOTAL                             241.0M

Model: MacBookPro11,2, BootROM MBP112.0138.B15, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.18f15
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: Thunderbolt Ethernet, Ethernet, en5
PCI Card: Apple 57762-A0, Ethernet Controller, Thunderbolt@195,0,0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: Internal Memory Card Reader
USB Device: ATEN  CS-1758/54
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1
Thunderbolt Device: Thunderbolt to Gigabit Ethernet Adapter, Apple Inc., 3, 5.5

**Comment by Qusic** [comment]
Path: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
PlugIn Path: /usr/local/Frameworks/Python.framework/Versions/2.7/Python

The python you compile ycmd with and that you run ycmd with should be the same. Try to enter the full path of python executable in the settings.

**Comment by cam5** [comment]
Hey, @bdsun, I'd have a look at what folks are saying over at https://github.com/Valloric/YouCompleteMe/issues/18
