### ISSUE TITLE
Update ycmd fail

### ISSUE THREAD

**Issue by rushcheyo** [Qusic/atom-youcompleteme#33]
Than I try to use make to build ycmd, but:

/Users/rushcheyo/.atom/packages/you-complete-me/ycmd/cpp/ycm/ClangCompleter/CompletionData.h:23:10: fatal error: 
      'clang-c/Index.h' file not found
#include \<clang-c/Index.h\>
               ^
1 error generated.
make[3]: *** [ycm/CMakeFiles/ycm_core.dir/CandidateRepository.cpp.o] Error 1
make[2]: *** [ycm/CMakeFiles/ycm_core.dir/all] Error 2
make[1]: *** [ycm/CMakeFiles/ycm_support_libs.dir/rule] Error 2
make: *** [ycm_support_libs] Error 2

**Comment by Qusic** [comment]
for installation guide and troubleshooting:
https://github.com/Valloric/YouCompleteMe/blob/master/README.md#installation
