### ISSUE TITLE
not work on windows 7 64bit

### ISSUE THREAD

**Issue by mars00772** [Qusic/atom-youcompleteme#35]
not work on windows 7 64bit，can you?

**Comment by mars00772** [comment]
I made the right config for atom-youcompleteme,now he said the native part of YCM must be recompiled to work.so I try using sublime-youcompleteme's YCMD.
now it seems that the YCMD server can not be start：
[YCM-ERROR] Error: connect ECONNREFUSED 127.0.0.1:41454
    at Object.exports._errnoException (util.js:814:11)

**Comment by Qusic** [comment]
Ycmd has some native components that you have to compile before using ycmd. Ycmd doesn't support Windows officially but it actually works.
