### ISSUE TITLE
Use yum_extra_conf.py per project

### ISSUE THREAD

**Issue by cHoco** [Qusic/atom-youcompleteme#39]
The plugin doesn't seem to load the .ycm_extra_conf.py in the project folder but only the global ycm_extra_conf defined in the settings.
Am I missing something?

**Comment by kkHAIKE** [comment]
are you enable legacy ycmd?

**Comment by cHoco** [comment]
No I didn't. I also tried enabling but it still doesn't work

**Comment by Qusic** [comment]
It works for me. You may open Atom in dev mode and check the log for more information.
