### ISSUE TITLE
Update `ycmd` fork for Rust support

### ISSUE THREAD

**Issue by Furyhunter** [Qusic/atom-youcompleteme#40]
Rust support is now merged into the upstream `ycmd` so for Atom to support it, the fork needs to merge those commits in. `ycmd` seems to have better support for Rust now than the existing Atom-specific plugins that call into cargo and racer directly.

**Comment by Qusic** [comment]
The upstream of ycmd has fixed the issues that I worked around in the fork and the fork is not needed any more. My winter vacation is coming soon and I will be able to work on it one or two weeks later.

**Comment by lilianmoraru** [comment]
The fork is not needed any more? Do you think we could compile it ourselves and it will work or you have to do some additional work?

**Comment by Furyhunter** [comment]
For rust support there's some additional work needed, but it also seems like some API changes have happened underneath. I can't get the current version of the extension working with the latest ycmd, the daemon won't start.

**Comment by Qusic** [comment]
Now this package uses the original ycmd instead of my fork and it should work for all ycmd-supported languages.

**Comment by Furyhunter** [comment]
Thanks!

**Comment by lilianmoraru** [comment]
Thank you!
