### ISSUE TITLE
'stdarg.h' file not found

### ISSUE THREAD

**Issue by rushcheyo** [Qusic/atom-youcompleteme#43]
![2016-01-19 13 20 50](https://cloud.githubusercontent.com/assets/11027474/12410383/828656f0-beaf-11e5-99b6-c044271135d8.png)

**Comment by Qusic** [comment]
it is likely that you haven't set up your ycm extra config file correctly.
https://github.com/Valloric/YouCompleteMe#c-family-semantic-completion-engine-usage

**Comment by rushcheyo** [comment]
@Qusic 但是在你更新之前这个配置都是正常的。

**Comment by rushcheyo** [comment]
@Qusic 我找到了一些原因，似乎 include path 被硬编码成了 ‘/usr/include’.
