### ISSUE TITLE
Include brief ycmd installation guidelines?

### ISSUE THREAD

**Issue by kbarros** [Qusic/atom-youcompleteme#45]
The atom-youcompleteme README currently points to YouCompleteMe's README regarding installation of the ymcd package. YouCompleteMe's README seems to require installation of Vim and Vundle in order to install ymcd. Is this truly required, or can ymcd be installed independently of Vim? (The goal is Atom integration, after all.) In either case, maybe a short note can be added to atom-youcompleteme's README.

**Comment by Qusic** [comment]
https://github.com/Valloric/ycmd#building

**Comment by scott-vsi** [comment]
It was not clear to me that you only need to install ycmd, and not YouCompleteMe. Or even that ycmd is a library that can be installed separately. Perhaps instead of "Install the package", you could say "Install ycmd" and provide the link to https://github.com/Valloric/ycmd#building.

**Comment by kbarros** [comment]
This comment https://www.reddit.com/r/rust/comments/43inzn/youcompleteme_sublime_plugin_gets_rust_support/czihb6n and associated discussion makes me think that the full YouCompleteMe Vim installation is currently required to get ycmd. However, it would good if an expert could way in.

**Comment by Qusic** [comment]
You only need to install ycmd to use this package. If you have installed YouCompleteMe for vim, the ycmd bundled can also be used with this package.

**Comment by Qusic** [comment]
Ok. I updated the link in README.md.
