### ISSUE TITLE
No semantic completer exists for filetypes: [u'php']

### ISSUE THREAD

**Issue by Dsazz** [Qusic/atom-youcompleteme#46]
Please, tell me how fix this error "No semantic completer exists for filetypes: [u'php']" ? In my VIM all works fine.

**Comment by Qusic** [comment]
What version of ycmd are you using?

**Comment by Dsazz** [comment]
18

**Comment by Dsazz** [comment]
Ok. I solve it. I removed the 'Atom' and all works fine )
