### ISSUE TITLE
Completions panel not staying open when typing (when completing from external libraries)

### ISSUE THREAD

**Issue by kasperientje** [Qusic/atom-youcompleteme#49]
I have a project with SDL and OpenGL. Completions within the project between the files are perfect. For both OpenGL and SDL the completions show up by pressing ctrl-space, but disappear when continue typing (or rather, defaults to 'normal' completions).

To be honest I'm not sure if this is an issue or just not a feature yet, so excuse me if that's the case.

Steps to reproduce:
1. Have a project including with (I think) any external library
2. Start typing a function, press <ctrl-space> to search completions
3. Continue typing, panel goes away

To illustrate - I press ctrl-space after the capital R: 
![f13b8bd0b94b3605cabb15e68eb8e4c8](https://cloud.githubusercontent.com/assets/17455539/13706274/b9124684-e7a4-11e5-8a2c-728a12342818.gif)

It would be really nice to have the panel stay open and continue filtering the found completions.

**Comment by Qusic** [comment]
fixed
