### ISSUE TITLE
Error: Bad Hmac

### ISSUE THREAD

**Issue by forivall** [Qusic/atom-youcompleteme#5]
Thanks for solving #3, now I'm getting a different error.

```
[YCM-CONSOLE] 2015-04-20 10:47:13,872 - INFO - Dropping request with bad HMAC.
    /home/forivall/.atom/packages/you-complete-me/lib/ycm-handler.coffee:97 
[YCM-ERROR] Error: Bad Hmac {stack: (...), message: "Bad Hmac"}
    /home/forivall/.atom/packages/you-complete-me/lib/ycm-handler.coffee:225

[YCM-ERROR] TypeError: Cannot read property 'completions' of undefined {stack: (...), message: "Cannot read property 'completions' of undefined"}
    /home/forivall/.atom/packages/you-complete-me/lib/ycm-provider.coffee:159
```
This occurs on every keystroke.

Is there some kind of config that needs to be set for ycm?

**Comment by Qusic** [comment]
Try updating ycm to the latest version.

**Comment by forivall** [comment]
Yup, that fixed it. I didn't expect ycmd to change that much in one week. :scream: 
The one other thing that would be nice is if you could enable youcompleteme for only certain languages, unless that's covered by the custom ycm_extra_conf.py. But that's something trivial enough that i could just submit a pull request without a bug report.

**Comment by AndiDog** [comment]
I'm getting "Bad Hmac" error every time with latest atom-youcompleteme and YCM from https://github.com/Valloric/YouCompleteMe.git at 674db42ee (latest commit). Working fine from vim.

**Comment by carlosjoserg** [comment]
Same here, complete output I'm getting is:

`
Error: Bad Hmac
    at IncomingMessage.<anonymous> (/home/carlos/.atom/packages/you-complete-me/lib/handler.coffee:180:24)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

Versions:
* Ubuntu 16.04 
* Atom 1.9.9
* ycm plugin 0.7.11
* ycmd (from synaptics 0+20160327+gitc3e6904-1)
* default_settings.json by ycmd install
