### ISSUE TITLE
Is there an equivalence of ycm_extra_conf_globallist?

### ISSUE THREAD

**Issue by dragonxlwang** [Qusic/atom-youcompleteme#50]
Like this:

```
 let g:ycm_extra_conf_globlist = ['~/workspace/*','~/Dropbox/workspace/*']`
```

I can setup safe zones within which extra_conf automatically get loaded. How can I get it down in ycm-atom?

This has been previously discussed in @19 and I still haven't figure out how to disable confirmation dialog.

--- Update

So far I found that on the ycmd side, I can customize it by changing the "default_settings.json" file, which is called by ``handler.coffee``:
```
  readDefaultOptions = new Promise (fulfill, reject) ->
    defaultOptionsFile = path.resolve atom.config.get('you-complete-me.ycmdPath'), 'ycmd', 'default_settings.json'
    fs.readFile defaultOptionsFile, encoding: 'utf8', (error, data) ->
      unless error?
        fulfill JSON.parse data
      else
        reject error
```

However, since my ycmd is also the vim's ycmd, I don't really want to make changes there (otherwise those change get wiped after PluginUpdate). It would be really better to expose some of those settings in atom as well...

Thanks,

**Comment by Qusic** [comment]
added in v0.7.2
