### ISSUE TITLE
atom snippets not working correctly

### ISSUE THREAD

**Issue by dragonxlwang** [Qusic/atom-youcompleteme#53]
As you can see, snippets disappears after I input more than one character. Please fix.
![untitled](https://cloud.githubusercontent.com/assets/15812510/14006720/4df14046-f13e-11e5-8244-b8c26355042f.gif)

**Comment by Qusic** [comment]
this cant be fixed for now. this package has to use a [higher priority](https://github.com/Qusic/atom-youcompleteme/blob/master/lib/provider.coffee#L11) than atom snippets, or completions such as std::vector will be overriden.

**Comment by dragonxlwang** [comment]
@Qusic , n00b in coffee script. I just compared atom-ycm with atom-clang, it seems that they used a different priority settings. Their completion seems not having this kind of problem IIRC. Maybe this can be helpful 

https://github.com/yasuyuky/autocomplete-clang/blob/master/lib/clang-provider.coffee

**Comment by Qusic** [comment]
One completion will override the other. You can't have both of them. It doesn't make sense to change the priority before we have better solution.

**Comment by dragonxlwang** [comment]
if I understand correctly, this is a issue with [autocomplete-plus](https://github.com/atom/autocomplete-snippets/issues/46)? Maybe ask them to consider allowing a larger pool of suggestions?

**Comment by Qusic** [comment]
Yes. autocomplete+ will merge completions to make each of them unique. https://github.com/atom/autocomplete-plus/blob/master/lib/autocomplete-manager.coffee#L318
