### ISSUE TITLE
Linter gets confused if multiple editor tabs are open to the same file

### ISSUE THREAD

**Issue by kentonv** [Qusic/atom-youcompleteme#54]
Hi, this plugin is amazing! I ran into trouble, though, when opening the same file in two tabs at once:

1. Open a file.
2. Right-click the tab and choose one of the "split" options. Now there are two copies of the file open.
3. Insert an error in the first tab, see it highlighted.
4. Fix the error in the second tab.

Expected result: The error message goes away in both tabs.
Actual result: The error message sticks around until you also edit the first tab.

**Comment by Qusic** [comment]
It seems an issue of linter itself.
