### ISSUE TITLE
No default config load, no python completion, any suggestions why?

### ISSUE THREAD

**Issue by mikoff** [Qusic/atom-youcompleteme#55]
Hello.
Today I decided to try atom for C and Python programming. Firstly  I thought that i will need several plugins to enable auto-completion for different languages, but than I discovered that youcompleteme extension is already here.
What I have done: Installed Atom 1.7.1, you-complete-me package 0.7.4, compiled ycmd server, added Ycmd path to the plugin settings and added "python" to enabled filetypes list.

What I am experiencing:
1) When I open my C-project folder and any c-file inside it atom-youcompleteme doesn't automatically loads .ycm_extra_conf, I have to press any hotkey combination, for example "alt+y g", after that the dialog about .ycm_extra_conf load pops up and auto-completion starts to work properly. (I have an opposite behavior in VIM, this dialog pops pup immediately).
2) The auto-completion doesn't work at all for Python, the hotkeys, such as "alt+y g" work, but only inside the current file. Could someone provide any suggestions where to dig? (because it works as expected in VIM and example_client.py script from ycmd folder returns correct results)

Thank you.

**Comment by Qusic** [comment]
1. Loading of extra config can also be triggered by lint request. maybe you can try enable Lint As You Type.
2. Only support for clang-family languages are enabled by default. See settings.

**Comment by mikoff** [comment]
Regarding 2: I edited "Enabled filetypes" settings string, now it looks like:
`c, cpp, objc, objcpp, python`
