### ISSUE TITLE
0.2.0不能工作

### ISSUE THREAD

**Issue by meritozh** [Qusic/atom-youcompleteme#6]
请问能否给个示例配置？
vim里YCM工作正常，但是atom里不能工作。

配置如下：
~/.vim/.ycm_extra_conf.py
/System/Library/Frameworks/Python.framework/Versions/2.7/Python
~/.vim/bundle/YouCompleteMe/third_party/ycmd

**Comment by Qusic** [comment]
python executable 写 `/usr/bin/python` 试试？
还不行的话看看console报的啥错

**Comment by meritozh** [comment]
@Qusic 嗯，解决了。不可以写~，必须是全路径。另外能否请教一下，如何配置YCM来补齐cocoa和OC？

**Comment by Qusic** [comment]
ycm对objc支持还不是很好，这个得先从ycm那边来解决
