### ISSUE TITLE
No function parameter completion at all (In C)

### ISSUE THREAD

**Issue by NebuKatWork** [Qusic/atom-youcompleteme#66]
Hi,

in my environment i’m unable to get function parameter completion displayed at all, writing C99. According to #48 it should be there in the completion-possibility-list, but not after selecting one possibility, right? It doesn’t show up at all for me though…

I’m using ycmd latest GIT (47304e1af6c7a9a18f5dd93723606185956145d1), you-complete-me 0.7.8 and atom 1.6.2.

Is there anything i’m missing?

Thanks!

**Comment by Qusic** [comment]
You can launch atom in dev mode and see the console. ycm plugin logs a lot of useful information.
