### ISSUE TITLE
porting to vscode?

### ISSUE THREAD

**Issue by agauniyal** [Qusic/atom-youcompleteme#69]
Would you mind porting your plugin to [vscode](https://code.visualstudio.com/), since no existing plugin serves the purpose of this atom plugin. [vscode](https://code.visualstudio.com/) feels much quicker and has an integrated debugger support for c++ too. The only thing remaining is c++ intellisense support. vscode plugins are also written in js itself so most of the work is already done here.

Looking forward to your reply :smile:

**Comment by Qusic** [comment]
https://github.com/richard1122/vscode-youcompleteme
