### ISSUE TITLE
Failed to spawn command

### ISSUE THREAD

**Issue by ccolon944** [Qusic/atom-youcompleteme#79]
This is the specific error I get.
Failed to spawn command /home/christian/anaconda3/bin/python3. Make sure /home/christian/anaconda3/bin/python3 is installed and on your PATH

[YCM] Error
Error: connect ECONNREFUSED 127.0.0.1:42399
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

I can use anaconda from terminal so I don't see why I am getting this path issue.
![screenshot from 2017-01-15 16-40-10](https://cloud.githubusercontent.com/assets/18058828/21966455/697b8b62-db41-11e6-8121-2653ae1ec69e.png)

**Comment by Qusic** [comment]
I have no idea what's going wrong. You can run `which python3` in your shell to see the full path to the python executable.
