### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by user-don** [Qusic/atom-youcompleteme#9]
I apologize for not being more specific, but with YouCompleteMe installed and a global conf file in my home directory, and using the settings below, I simply get no autocomplete actions when editing a C++ file. 

Global Extra Config: ~/.ycm_extra_conf.py
Python Executable: /usr/bin/python
YCMD Path: /home/.vim/bundle/YouCompleteMe/third_party/ycmd

Is there a way for me to debug this so that I can provide more information?

Thanks

**Comment by Qusic** [comment]
See console output
