### ISSUE TITLE
YouCompleteMe not working

### ISSUE THREAD

**Issue by YuntianLi91** [Qusic/atom-youcompleteme#94]
Hi guys, I have installed the You-Complete-Me through package manager and set all the path correct, however I still have this error message and YCM doesn't work:

[YCM]Error: ENOENT: no such file or directory, open '~/.vim/bundle/YouCompleteMe/third_party/ycmd'

Does anyone know how to solve this problem ?
My system is Ubuntu 18.04

**Comment by Qusic** [comment]
you have to use absolute paths, without the tilde `~`
